---
version: "3.7"

services:
  proxy:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      # - backend
      - frontend

  # queue:
  #   image: redis

  # db:
  #   image: postgres:13
  #   restart: always
  #   env_file:
  #     - .env
  #   environment:
  #     - PGDATA=/var/lib/postgresql/data/pgdata
  #   volumes:
  #     - app-db-data:/var/lib/postgresql/data:cached

  # worker:
  #   command: celery worker -A app.worker -l info -Q main-queue -c 1
  #   env_file:
  #     - .env
  #   environment:
  #     - SERVER_NAME=${DOMAIN?Variable not set}
  #     - SERVER_HOST=https://${DOMAIN?Variable not set}
  #   depends_on:
  #     - db
  #     - queue

  # flower:
  #   image: mher/flower
  #   command: celery flower --broker=redis://redis:6379/0 --port=5555
  #   depends_on:
  #     - queue

  # backend:
  #   depends_on:
  #     - db
  #   environment:
  #     - SERVER_NAME=${DOMAIN?Variable not set}
  #     - SERVER_HOST=https://${DOMAIN?Variable not set}

  frontend:
    build:
      context: ./frontend
      args:
        FRONTEND_ENV: ${FRONTEND_ENV-production}

volumes:
  app-db-data:
