---
version: "3.7"

services:
  # worker:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   environment:
  #     - SERVER_NAME=${DOMAIN?Variable not set}
  #     - SERVER_HOST=http://${DOMAIN?Variable not set}
  #   volumes:
  #     - ./backend:/app/:cached

  # flower:
  #   ports:
  #     - 5555:5555

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
  #   volumes:
  #     - ./backend:/app/:cached
  #   environment:
  #     - SERVER_NAME=${DOMAIN?Variable not set}
  #     - SERVER_HOST=http://${DOMAIN?Variable not set}

  frontend:
    build:
      context: ./frontend
      args:
        FRONTEND_ENV: dev
