---
version: "3.9"

services:
  nginx:
    profiles:
      - proxy

  postgres:
    ports:
      - 5432:5432

  redis:
    ports:
      - 6379:6379

  pgadmin:
    ports:
      - 5050:5050

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - 8000:8000
    volumes:
      - ./backend:/infilmation:cached
    profiles:
      - backend

  frontend:
    build:
      context: ./frontend
      args:
        FRONTEND_ENV: dev
    profiles:
      - frontend
