---
version: "3.9"

services:
  backend:
    image: infilmation/backend:latest
    environment:
      - PERSIST_FILM_DATA=True
      - TMDB_API_KEY=${TMDB_API_KEY}

  frontend:
    image: infilmation/frontend:latest

  pgadmin:
    profiles:
      - pgadmin
