---
version: "3.7"

services:
  # worker:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   environment:
  #     - SERVER_NAME=${DOMAIN?Variable not set}
  #     - SERVER_HOST=http://${DOMAIN?Variable not set}
  #   volumes:
  #     - ./backend:/app/:cached

  # flower:
  #   ports:
  #     - 5555:5555

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8888:8000
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./backend/app:/code/app

  frontend:
    build:
      context: ./frontend
      args:
        FRONTEND_ENV: dev
