version: '3.8'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python app/main.py
    volumes:
      - ./backend/app:/app:cached
    ports:
      - '8888:8888'
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app:cached
    ports:
      - '3000:3000'

volumes:
  app-db-data:
