"""Add status to batch

Revision ID: 3da7ccdf5976
Revises: 2bdb811bc5c2
Create Date: 2021-03-22 09:41:06.679562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3da7ccdf5976'
down_revision = '2bdb811bc5c2'
branch_labels = None
depends_on = None


def upgrade():
    batchstatus = postgresql.ENUM('pending', 'started', 'finished', name='batchstatus')
    batchstatus.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('completion', sa.Float(), nullable=True))
    op.add_column('batch', sa.Column('status', postgresql.ENUM('pending', 'started', 'finished', name='batchstatus'), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # op.execute("DROP TYPE batchstatus;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batch', 'status')
    op.drop_column('batch', 'completion')
    # ### end Alembic commands ###
