"""Increase plot column length

Revision ID: 969a356889d4
Revises: 25dd5d936621
Create Date: 2021-03-23 13:28:34.476408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969a356889d4'
down_revision = '25dd5d936621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.execute('ALTER TABLE film ALTER COLUMN plot TYPE TEXT')



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.execute('ALTER TABLE film ALTER COLUMN plot TYPE VARCHAR')
