"""Add current film

Revision ID: a196f7b0d45b
Revises: 969a356889d4
Create Date: 2021-03-24 09:10:32.547771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a196f7b0d45b'
down_revision = '969a356889d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('current_film', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batch', 'current_film')
    # ### end Alembic commands ###
