"""Create genre, director and actor tables

Revision ID: 25dd5d936621
Revises: d0530e87ed0e
Create Date: 2021-03-22 14:04:15.665341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25dd5d936621'
down_revision = 'd0530e87ed0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('director',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('actor_film',
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], )
    )
    op.create_table('director_film',
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], )
    )
    op.create_table('film_genre',
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], )
    )
    op.drop_column('film', 'directors')
    op.drop_column('film', 'cast')
    op.drop_column('film', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('genres', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('film', sa.Column('cast', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('film', sa.Column('directors', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('film_genre')
    op.drop_table('director_film')
    op.drop_table('actor_film')
    op.drop_table('genre')
    op.drop_table('director')
    op.drop_table('actor')
    # ### end Alembic commands ###
