"""First migration

Revision ID: 55259ccd3c01
Revises: 
Create Date: 2021-03-19 10:02:18.350150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55259ccd3c01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=True),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('genres', sa.String(length=255), nullable=True),
    sa.Column('runtime', sa.String(length=255), nullable=True),
    sa.Column('cast', sa.String(length=255), nullable=True),
    sa.Column('directors', sa.String(length=255), nullable=True),
    sa.Column('plot', sa.String(length=255), nullable=True),
    sa.Column('imtitle', sa.String(length=255), nullable=True),
    sa.Column('imyear', sa.Integer(), nullable=True),
    sa.Column('imscore', sa.String(length=255), nullable=True),
    sa.Column('imlow_confidence', sa.Boolean(), nullable=True),
    sa.Column('mtc_title', sa.String(length=255), nullable=True),
    sa.Column('mtc_year', sa.Integer(), nullable=True),
    sa.Column('mtc_score', sa.String(length=255), nullable=True),
    sa.Column('mtc_low_confidence', sa.Boolean(), nullable=True),
    sa.Column('rt_title', sa.String(length=255), nullable=True),
    sa.Column('rt_year', sa.Integer(), nullable=True),
    sa.Column('rt_tomato_score', sa.String(length=255), nullable=True),
    sa.Column('rt_audience_score', sa.String(length=255), nullable=True),
    sa.Column('rt_low_confidence', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_film_id'), 'film', ['id'], unique=False)
    op.create_table('batch_film',
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batch_film')
    op.drop_index(op.f('ix_film_id'), table_name='film')
    op.drop_table('film')
    op.drop_table('batch')
    # ### end Alembic commands ###
