"""Move to array columns

Revision ID: d0530e87ed0e
Revises: 3da7ccdf5976
Create Date: 2021-03-22 13:42:59.382835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0530e87ed0e'
down_revision = '3da7ccdf5976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batch', 'completion',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('batch', 'status',
               existing_type=postgresql.ENUM('pending', 'started', 'finished', name='batchstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batch', 'status',
               existing_type=postgresql.ENUM('pending', 'started', 'finished', name='batchstatus'),
               nullable=True)
    op.alter_column('batch', 'completion',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
