"""batch table

Revision ID: 64ac9cabb89b
Revises: 
Create Date: 2021-03-17 23:15:08.095651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ac9cabb89b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'batch', 'task', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'batch', type_='foreignkey')
    op.drop_column('batch', 'task_id')
    # ### end Alembic commands ###
