"""update rating columns

Revision ID: 8cbdfed375e8
Revises: a31843cbd9d7
Create Date: 2021-11-16 13:11:23.789430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cbdfed375e8'
down_revision = 'a31843cbd9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='films',
        column_name='mtc_rating',
        type_=sa.String(length=255),
    )
    op.alter_column(
        table_name='films',
        column_name='rt_tomato_rating',
        type_=sa.String(length=255),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='films',
        column_name='mtc_rating',
        type_=sa.Integer(),
    )
    op.alter_column(
        table_name='films',
        column_name='rt_tomato_rating',
        type_=sa.Integer(),
    )
    # ### end Alembic commands ###
