"""add tmdb_id

Revision ID: c4f273f6f462
Revises: 8cbdfed375e8
Create Date: 2021-11-18 17:13:04.006016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f273f6f462'
down_revision = '8cbdfed375e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('tmdb_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'tmdb_id')
    # ### end Alembic commands ###
